#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.1.6ubuntu2
dpkg-maintscript-helper rm_conffile /etc/linuxmint/adjustments/15-mintlocale.menu 1.4.7~ -- "$@"
# End automatically added section
